// import Image from "next/image";
import useStyles from "./styles";
import { Image } from "@mantine/core";
const Hero = () => {
  const { classes } = useStyles();
  return (
    <div className={classes.container}>
      <Image
        radius="md"
        src="/assets/hero-stripradar.png"
        alt="ClubChaser main page image, (generated by Midjourney)"
        className={classes.heroImage}
      />
    </div>
  );
};

export default Hero;
